name: Nativevotes Autobuild
# modified from https://github.com/nosoop/NinjaBuild-SMPlugin/blob/master/contrib/github-workflow/build-on-version-tag-push.yml

on:
  push:
    branches: [ master ]

jobs:
  run:
    name: Run action
    runs-on: ubuntu-22.04

    # skip build on '[ci skip]'
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup SourcePawn 1.10 Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.10.x"

    - name: Compile plugins 1.10
      shell: bash
      run: |
        bash .github/nv_compile.sh

    - name: Setup SourcePawn 1.11 Compiler
      uses: rumblefrog/setup-sp@master
      with:
        version: "1.11.x"

    - name: Compile plugins 1.11
      shell: bash
      run: |
        bash .github/nv_compile.sh
        bash

    - name: Set Commit Hash
      id: commit_info
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Tag version
      id: tag
      uses: anothrNick/github-tag-action@1.34.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ needs.build_and_push.outputs.tag }}

    - name: Check created tag
      id: check_tagged
      run: |
        echo "::set-output name=tagged::${{ (steps.check_tag.outputs.exists == 'false') && (steps.tag.outputs.new_tag == steps.tag.outputs.tag) }}"

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/nativevotes*"
        tag: ${{ needs.tag_version.outputs.tag }}
        token: ${{ secrets.GITHUB_TOKEN }}

